config/routes.rb
Rails.application.routes.draw do
  root to: "books#index"
  resources :books, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image

  validates :title, :story, :quote, :thought, presence: true

  validates :category_id, presence: true, numericality: { other_than: 1 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'この本のジャンルを教えてください！' },
    { id: 2, name: '文学・評論' },
    { id: 3, name: 'ノンフィクション' },
    { id: 4, name: 'ビジネス・経済' },
    { id: 5, name: '歴史・地理' },
    { id: 6, name: '政治・社会' },
    { id: 7, name: '芸能・エンターテインメント' },
    { id: 8, name: 'アート・建築・デザイン' },
    { id: 9, name: '人文・思想・宗教' },
    { id: 10, name: '暮らし・健康・料理' },
    { id: 11, name: 'サイエンス・テクノロジー' },
    { id: 12, name: '趣味・実用' },
    { id: 13, name: '教育・自己啓発' },
    { id: 14, name: 'スポーツ・アウトドア' },
    { id: 15, name: '事典・年鑑・本・ことば' },
    { id: 16, name: '音楽' },
    { id: 17, name: '旅行・紀行' },
    { id: 18, name: '絵本・児童書' },
    { id: 19, name: 'コミックス' },
    { id: 20, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
   @books = Book.order("created_at DESC")
  end

  def new
    @books = Book.new
  end

  def create
    #binding.pry
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  private
  def book_params
    params.permit(:image, :title, :story, :quote, :thought, :category_id, :evaluation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">ReadMore!</a></h1>
        <div class="user_nav grid-6">
          <%= link_to '投稿する', new_book_path, class: "post" %>
        </div>
      </div>
</header>
<div class=each>↓投稿一覧↓</div>
<div class="contents row">
  <% @books.each do |book| %>
    <div class="book">
      <div class="book-title">
        『<%= link_to book.title, book_path(book.id) %>』
      </div>
      <%= image_tag book.image.variant(resize: '500x500'), class: 'book-image' if book.image.attached? %>
      <div class="book-category">
        ジャンル：<%= book.category.name %>
      </div>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<h1 class="grid-6"><a href="/">ReadMore!</a></h1>
<%= form_with model: @book, url:books_path, local: true do |f| %>
  <div class="book-box">
    <div class = todo>読んだ本を投稿しよう！</div>
    <div class="img-upload">
      <div class="click-upload">
        クリックして本の画像をアップロードしてください！<br>
        <%= f.file_field :image, id:"book-image" %>
      </div>
    </div>
    <%= f.text_field :title, class:"title", placeholder:"この本のタイトルを教えてください！" %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"category-select"}) %>
    <%= f.text_area :story, class:"story", placeholder:"この本のあらすじを教えてください！" %>
    <%= f.text_area :quote, class:"quote", placeholder:"好きな箇所を引用してください" %>
    <%= f.text_area :thought, class:"thought", placeholder:"この本の感想を教えてください！" %>
    <form type="get" action="#">
     この本の評価を教えてください！
      <div class="evaluation">
        <input id="star1" type="radio" name="star" value="5" />
        <label for="star1"><span class="text">最高</span>★</label>
        <input id="star2" type="radio" name="star" value="4" />
        <label for="star2"><span class="text">良い</span>★</label>
        <input id="star3" type="radio" name="star" value="3" />
        <label for="star3"><span class="text">普通</span>★</label>
        <input id="star4" type="radio" name="star" value="2" />
        <label for="star4"><span class="text">悪い</span>★</label>
        <input id="star5" type="radio" name="star" value="1" />
        <label for="star5"><span class="text">最悪</span>★</label>
      </div>
    </form>

    <%= f.submit "投稿する" ,class:"btn" %>
    <%= link_to 'もどる', root_path %>
  </div>
<% end %>

app/views/books/show.html.erb
<%= @book.title %>の詳細ページ
<div class = 'book-show'>
  <div class="book-title">
    『<%= @book.title %>』
  </div>
  <%= image_tag @book.image.variant(resize: '500x500'), class: 'book-image' if @book.image.attached? %>
  <div class="book-category">
    ジャンル：<%= @book.category.name %>
  </div>
  <div class="book-story">
    あらすじ：<%= @book.story %>
  </div>
  <div class="book-quote">
    引用：<%= @book.quote %>
  </div>
  <div class="book-thought">
    感想：<%= @book.thought %>
  </div>
</div>
<%= link_to 'もどる', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <title>ReadMore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    

    

  </head>

  <body>
    
    <%= yield %>
  </body>
</html>